# Generated by Django 3.2.4 on 2021-07-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(height_field=100, upload_to=None, verbose_name='Imagem Prévia', width_field=100)),
                ('nome_prod', models.TextField(max_length=100, verbose_name='Nome do Produto')),
                ('tipo_prod', models.TextField(max_length=100, verbose_name='Tipo de Produto')),
                ('prec_prod', models.TextField(max_length=100, verbose_name='Preço')),
            ],
        ),
    ]
