# Generated by Django 3.2.4 on 2021-07-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome_prod',
            field=models.CharField(max_length=100, verbose_name='Nome do Produto'),
        ),
    ]
