# Generated by Django 3.2.4 on 2021-07-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_produto_nome_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='prec_prod',
            field=models.IntegerField(max_length=100, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo_prod',
            field=models.CharField(max_length=100, verbose_name='Tipo de Produto'),
        ),
    ]
