# Generated by Django 3.2.4 on 2021-07-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_produto_prec_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='img',
            field=models.ImageField(upload_to='static', verbose_name='Imagem Prévia'),
        ),
    ]
