# Generated by Django 3.2.4 on 2021-07-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_produto_prec_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='prec_prod',
            field=models.IntegerField(default=5, verbose_name='Preço'),
            preserve_default=False,
        ),
    ]
