# Generated by Django 3.2.4 on 2021-07-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_produto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descr',
            field=models.TextField(default=23, max_length=2000, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='img',
            field=models.ImageField(null=True, upload_to='static', verbose_name='Imagem Prévia'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='prec_prod',
            field=models.FloatField(verbose_name='Preço'),
        ),
    ]
