# Generated by Django 3.2.4 on 2021-07-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210728_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='promovido',
            field=models.BooleanField(default=False, verbose_name='Promovido'),
        ),
    ]
