# Generated by Django 3.2.4 on 2021-08-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_produto_promovido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='disponibilidade',
            field=models.BooleanField(default=False, verbose_name='disponivel'),
        ),
    ]
