# Generated by Django 3.2.4 on 2021-08-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_produto_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data',
        ),
    ]
